### PR TITLE
need to explicitly ask for test-unit now

### LINKED ISSUE #7: Cant run test suite
Cannot run test suite, readme says it's just `rake test` but this is what i get (after bundle update of course)
```
user@user-pc:~/find_as_hashes$ rake test
/home/user/.rvm/rubies/ruby-2.2.1/bin/ruby -I"lib:lib:test"  "/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/active_resource_test.rb" "test/find_as_hashes_test.rb" 
/home/user/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require': cannot load such file -- test/unit (LoadError)
        from /home/user/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `block in require'
        from /home/user/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
        from /home/user/.rvm/gems/ruby-2.2.1/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
        from /home/user/find_as_hashes/test/test_helper.rb:2:in `<top (required)>'
        from /home/user/find_as_hashes/test/active_resource_test.rb:1:in `require'
        from /home/user/find_as_hashes/test/active_resource_test.rb:1:in `<top (required)>'
        from /home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb:15:in `require'
        from /home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb:15:in `block in <main>'
        from /home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `select'
        from /home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:lib:test"  "/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/active_resource_test.rb" "test/find_as_hashes_test.rb" ]
/home/user/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/home/user/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

### PR DESCRIPTION
**Pull request by jphenow**
Fixes #7 

@anfleene Would you enable Travis? We should probably add a few gemfiles and ruby versions to this. Also there are 2 warnings per test, another set of :eyes: would be cool if you get a moment in the next few days.

### CODE REVIEW

**Comment by anfleene** [comment]
@jphenow appears to be working.

**Comment by jphenow** [comment]
Oh I must've just been impatient

**Comment by anfleene** [comment]
:shipit:

**Comment by jphenow** [comment]
Not going to do a new release since this is all backoffice stuff

**Pull request merged**
